//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Dynamics.WebApi.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceMensaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Dynamics.WebApi.Resource.ResourceMensaje", typeof(ResourceMensaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - El Registro no pudo ser insertado, por favor verificar..
        /// </summary>
        internal static string ErrorClieRes1 {
            get {
                return ResourceManager.GetString("ErrorClieRes1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - El Registro no pudo ser actualizado, por favor verificar..
        /// </summary>
        internal static string ErrorClieRes2 {
            get {
                return ResourceManager.GetString("ErrorClieRes2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Operacion Cancelada, por favor verificar el Contratista y el Representante Legal..
        /// </summary>
        internal static string ErrorContratistaIN {
            get {
                return ResourceManager.GetString("ErrorContratistaIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - El Representante Legal no estan registrados, por favor verificar..
        /// </summary>
        internal static string ErrorContratistaNR {
            get {
                return ResourceManager.GetString("ErrorContratistaNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Operacion Cancelada, por favor verificar el codigo del PAP y su codigo de Proyecto..
        /// </summary>
        internal static string ErrorProyectoPSIN {
            get {
                return ResourceManager.GetString("ErrorProyectoPSIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - El codigo de Proyecto puede no estar registrado o no estar activo, por favor Verificar.
        /// </summary>
        internal static string ErrorProyectoPSNR {
            get {
                return ResourceManager.GetString("ErrorProyectoPSNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - Operacion Cancelada, por favor verificar el Codigo del PAP y el Codigo de Red..
        /// </summary>
        internal static string ErrorPsIN {
            get {
                return ResourceManager.GetString("ErrorPsIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - La Red no esta registrada, por favor verificar..
        /// </summary>
        internal static string ErrorPsNR {
            get {
                return ResourceManager.GetString("ErrorPsNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Operacion Cancelada, por favor verificar el Id y Los Contratistas y SubContratistas Asociados..
        /// </summary>
        internal static string ErrorRedContIN {
            get {
                return ResourceManager.GetString("ErrorRedContIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - El Contratista o el SubContratista no estan registrados, por favor verificar..
        /// </summary>
        internal static string ErrorRedContNR {
            get {
                return ResourceManager.GetString("ErrorRedContNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - Operacion Finalizada con exito.
        /// </summary>
        internal static string SuccessMessage {
            get {
                return ResourceManager.GetString("SuccessMessage", resourceCulture);
            }
        }
    }
}
